### PR TITLE
Enablelint1

### PR DESCRIPTION
**Pull request by yungez**

### CODE REVIEW

**Comment by ZhijunZhao** [comment]
To make it work, I think you need to add one gulpfile.js

**Comment by yungez** [comment]
@ZhijunZhao , no necessary, just run node_modules/.bin/eslint *.js

**Comment by ZhijunZhao** [comment]
Then, please cleanup all the errors from running 'node_modules/.bin/eslint *.js'. :)

**Review by zikalino — APPROVED** [review]
well, it's ok to merge these changes, but need to resolve conflicts first

**Comment by yungez** [comment]
I don't have permission to merge into master branch. could anyone help to grant permission? thanks.

**Pull request merged**
